### PR TITLE
LoRA loading and LoRA application

### PR DESCRIPTION
**Pull request by saddam213**
PR to introduce LoRA (Low Rank Adaptation) support

Adding most of this to the `OnnxStack.Core` as LoRA will be used for other projects outside `StableDiffusion`(Text Generation etc)

- [ ] `IOnnxModelService` to load/unload LoRA files
- [ ] New `IOnnxAdaperService` to manage LoRA application, support multiple applications
- [ ] Support Export of models with applied LoRA?
- [ ] Add support in `IStableDiffusionService` for `IOnnxAdaperService`
- [ ] Add UI support for selection/applying LoRA models 

Research Links
https://medium.com/openvino-toolkit/enable-lora-weights-with-stable-diffusion-controlnet-pipeline-94fb06c86ea2

Discussion about this feature
https://github.com/saddam213/OnnxStack/discussions/16

### CODE REVIEW

**Comment by Amin456789** [comment]
new lcm's 1.5 lora is very good if onnxstack can support it at some point!
https://huggingface.co/latent-consistency/lcm-lora-sdv1-5/tree/main

very low at size, can generate very good images at 4 steps

**Comment by saddam213** [comment]
Looks like I went down the wrong rabbit whole with the first implementation

However I think this may be the route
https://github.com/microsoft/onnxruntime/blob/main/csharp/test/Microsoft.ML.OnnxRuntime.Tests.Common/TrainingTest.cs

**Comment by Amin456789** [comment]
this repo just released lora and lcm lora=
https://github.com/leejet/stable-diffusion.cpp
it is a c++ sd project, it is using ggml though but maybe u can get help from its code as it is c++ related

**Comment by saddam213** [comment]
https://github.com/microsoft/Olive/blob/main/examples/directml/stable_diffusion/user_script.py#L35

**Comment by ForserX** [comment]
https://github.com/ForserX/StableDiffusionUI/blob/master/data/repo/diffusion_scripts/modules/onnx/lora.py

**Comment by saddam213** [comment]
Not possible at this time, Closing

**Pull request closed without merging**
