### PR TITLE
Added Async suffix to any methods that returned a Task or Task<> and …

### PR DESCRIPTION
**Pull request by riddlemd**
Noticed there's some inconsistencies with naming convention, fixed the async ones.

### CODE REVIEW

**Comment by saddam213** [comment]
Nice, thanks for the contribution

**Comment by saddam213** [comment]
Just meged this in and it broke the unit test, I should have checked fist, my bad

Are you able to update the UnitTest call to the `ModelLoad` and do a PR, im away from my PC right now

May have to load the OnnxStackCore.sln

**Comment by riddlemd** [comment]
Done. Might want to include Integration/Unit Tests in the main solution -- did not even notice they where there.
https://github.com/saddam213/OnnxStack/pull/29

**Comment by saddam213** [comment]
Yeah was just added yesterday and I already forgot, lol

**Pull request merged**
