### PR TITLE
Realtime Stable-Diffusion

### PR DESCRIPTION
**Pull request by saddam213**
This is a PR for the Realtime Stable-Diffusion(RTSD)

- [x] Add Realtime Automation option
- [x] TextToImage support
- [x] ImageToImage support
- [x] Inpaint support
- [x] Live Paint
- [x] Move realtime enable to main option view
- [x] Disable Automation when realtime is running
- [x] Initial canvas color picker
- [x] Recent color toolbar
- [x] Mouse wheel brushsize
- [x] Indicator that realtime is running (red dot or something)
- [x] Set a seed when enabling Realtime

[https://www.youtube.com/watch?v=U1qL-XuHT5o](https://www.youtube.com/watch?v=U1qL-XuHT5o)

### CODE REVIEW

**Comment by saddam213** [comment]
TextToImage is working is anyone wants to pull the branch and test

**Comment by Amin456789** [comment]
beautiful, thanks! that live paint will be lots of fun!

**Comment by saddam213** [comment]
> beautiful, thanks! that live paint will be lots of fun! please bring it to LCM too if possible

It supports all models :), LCM is best because its fastest

**Comment by Amin456789** [comment]
nice thanks!

**Comment by saddam213** [comment]
LOL, it works, and its epic

image

**Comment by Amin456789** [comment]
yea it is cool! release it ASAP! :D

**Pull request merged**
